# Generated by Django 4.2 on 2023-05-07 03:55

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogpost_options_remove_blogpost_publish_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.FileField(default='blog_images/default.png', upload_to=blog.models.user_directory_path),
        ),
    ]
